"""Phase 7.7 — shareable pilot/review progress reports.

Reports summarize an integrity-checked pilot session without exposing photo paths,
file identifiers, catalogue contents, or source image data. Operational runs are
supporting diagnostics only and never become archive evidence.
"""
from __future__ import annotations

import json
import os
import tempfile
import zipfile
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path

from ppa.activity_runs import ActivityRun, load_activity_runs
from ppa.pilot_audit import PilotAuditSnapshot, compare_pilot_audits
from ppa.pilot_session import PilotSession

REPORT_SCHEMA = "ppa-review-progress/1"


@dataclass(frozen=True)
class ProgressMetric:
    label: str
    baseline: int
    current: int
    delta: int


@dataclass(frozen=True)
class CheckpointProgress:
    sequence: int
    label: str
    captured_at: str
    usable_chronology: int
    confirmed_current: int
    unresolved: int
    stale_decisions: int
    actionable_review: int


@dataclass(frozen=True)
class RunSummary:
    run_id: str
    operation: str
    started_at: str
    outcome: str
    elapsed_ms: int | None


@dataclass(frozen=True)
class ReviewProgressReport:
    schema: str
    generated_at: str
    session_id: str
    session_status: str
    scope: str
    total_files: int
    metrics: tuple[ProgressMetric, ...]
    checkpoints: tuple[CheckpointProgress, ...]
    operational_runs: tuple[RunSummary, ...]
    current_integrity_flags: int
    integrity_status: str
    report_source_writes: int
    explicit_exclusions: tuple[str, ...]

    def to_dict(self) -> dict:
        return asdict(self)

    def to_json(self, *, pretty: bool = True) -> str:
        return json.dumps(self.to_dict(), indent=2 if pretty else None,
                          sort_keys=True, separators=None if pretty else (",", ":"))


def _scope_label(session: PilotSession) -> str:
    if session.explicit_file_ids is not None:
        return f"explicit selection ({len(session.explicit_file_ids)} files)"
    if session.directory_prefix:
        return "scoped directory"
    return "entire library"


def _effective_snapshot(session: PilotSession,
                        current: PilotAuditSnapshot | None) -> PilotAuditSnapshot:
    if current is not None:
        return current
    if session.status == "closed" and session.final is not None:
        return session.final
    if session.checkpoints:
        return session.checkpoints[-1].snapshot
    return session.baseline


def _scope_key(session: PilotSession) -> tuple:
    return session.library_root, session.directory_prefix, session.explicit_file_ids


def _snapshot_scope(s: PilotAuditSnapshot) -> tuple:
    return s.library_root, s.directory_prefix, s.explicit_file_ids


def _scope_matches_run(run: ActivityRun, session: PilotSession) -> bool:
    if not run.events:
        return False
    start = next((e for e in run.events if e.phase == "start"), run.events[0])
    detail = start.detail or {}
    # Only include operations whose structured start event proves the same scope.
    if detail.get("library_id") != session.library_id:
        return False
    if "directory" in detail and detail.get("directory") != session.directory_prefix:
        return False
    expected_n = None if session.explicit_file_ids is None else len(session.explicit_file_ids)
    if "explicit_files" in detail and detail.get("explicit_files") != expected_n:
        return False
    return True


def _in_window(run: ActivityRun, start: str, end: str) -> bool:
    # All timestamps are UTC ISO-8601 generated by PPA, so lexical order is stable.
    return bool(run.started_at) and start <= run.started_at <= end


def build_review_progress_report(session: PilotSession,
                                 current: PilotAuditSnapshot | None = None,
                                 *, activity_runs: tuple[ActivityRun, ...] = (),
                                 generated_at: str | None = None) -> ReviewProgressReport:
    """Build a path-free, file-id-free progress summary for one validated pilot."""
    snap = _effective_snapshot(session, current)
    if _snapshot_scope(snap) != _scope_key(session):
        raise ValueError("review report snapshot scope differs from pilot session")
    comparison = compare_pilot_audits(session.baseline, snap)

    pairs = (
        ("Usable chronology", comparison.usable_chronology),
        ("Confirmed current", comparison.confirmed_current),
        ("Current proposals", comparison.proposed_current),
        ("Unresolved", comparison.unresolved),
        ("Stale decisions", comparison.stale_decisions),
        ("Conflicts", comparison.conflicts),
        ("Actionable review", comparison.actionable_review),
        ("Anchor questions", comparison.anchor_questions),
    )
    metrics = tuple(ProgressMetric(label, d.before, d.after, d.delta) for label, d in pairs)
    checkpoints = tuple(
        CheckpointProgress(cp.sequence, cp.label, cp.captured_at,
                           cp.snapshot.usable_chronology.count,
                           cp.snapshot.confirmed_current.count,
                           cp.snapshot.unresolved.count,
                           cp.snapshot.stale_decisions.count,
                           cp.snapshot.actionable_review.count)
        for cp in session.checkpoints
    )
    end = snap.generated_at
    matching_runs = tuple(
        RunSummary(r.run_id, r.operation, r.started_at, r.outcome, r.elapsed_ms)
        for r in activity_runs
        if _in_window(r, session.baseline.generated_at, end) and _scope_matches_run(r, session)
    )
    matching_runs = tuple(sorted(matching_runs, key=lambda r: (r.started_at, r.run_id)))
    integrity_flags = sum(int(v) for v in snap.integrity_counts.values())
    return ReviewProgressReport(
        REPORT_SCHEMA,
        generated_at or datetime.now(timezone.utc).isoformat(),
        session.session_id,
        session.status,
        _scope_label(session),
        snap.total_files,
        metrics,
        checkpoints,
        matching_runs,
        integrity_flags,
        "clear" if integrity_flags == 0 else "attention",
        0,
        (
            "catalogue database", "source photos", "thumbnails", "photo file ids",
            "absolute library paths", "directory names", "raw log messages", "pilot session artifact",
        ),
    )


def concise_text(report: ReviewProgressReport) -> str:
    lines = [
        "PPA Phase 7 Review Progress", "===========================", "",
        f"Session: {report.session_id}",
        f"Status: {report.session_status.upper()}",
        f"Scope: {report.scope}",
        f"Files in scope: {report.total_files}", "",
        "BASELINE -> CURRENT", "-------------------",
    ]
    for m in report.metrics:
        sign = "+" if m.delta > 0 else ""
        lines.append(f"{m.label:20} {m.baseline:6} -> {m.current:6}  ({sign}{m.delta})")
    lines += ["", "Integrity", "---------",
              f"Current integrity flags: {report.current_integrity_flags}",
              f"Integrity status: {report.integrity_status}",
              f"Source writes by report: {report.report_source_writes}", "",
              f"Checkpoints: {len(report.checkpoints)}",
              f"Matching operational runs: {len(report.operational_runs)}"]
    return "\n".join(lines)


def markdown_text(report: ReviewProgressReport) -> str:
    lines = [
        "# PPA Phase 7 Review Progress Report", "",
        f"- Session: `{report.session_id}`",
        f"- Status: **{report.session_status.upper()}**",
        f"- Scope: {report.scope}",
        f"- Files in scope: {report.total_files}", "",
        "## Baseline to current", "",
        "| Metric | Baseline | Current | Delta |", "|---|---:|---:|---:|",
    ]
    for m in report.metrics:
        sign = "+" if m.delta > 0 else ""
        lines.append(f"| {m.label} | {m.baseline} | {m.current} | {sign}{m.delta} |")
    lines += ["", "## Integrity", "",
              f"- Current integrity flags: **{report.current_integrity_flags}**",
              f"- Integrity status: **{report.integrity_status.upper()}**",
              f"- Source writes performed by this report: **{report.report_source_writes}**"]
    if report.checkpoints:
        lines += ["", "## Checkpoints", "",
                  "| # | Label | Usable | Confirmed | Unresolved | Stale | Actionable |",
                  "|---:|---|---:|---:|---:|---:|---:|"]
        for c in report.checkpoints:
            lines.append(f"| {c.sequence} | {c.label or 'checkpoint'} | {c.usable_chronology} | "
                         f"{c.confirmed_current} | {c.unresolved} | {c.stale_decisions} | {c.actionable_review} |")
    if report.operational_runs:
        lines += ["", "## Matching operational runs", "",
                  "| Started | Run | Operation | Outcome | Duration |",
                  "|---|---|---|---|---:|"]
        for r in report.operational_runs:
            duration = "" if r.elapsed_ms is None else f"{r.elapsed_ms / 1000:.1f}s"
            lines.append(f"| {r.started_at} | `{r.run_id}` | {r.operation} | {r.outcome} | {duration} |")
    lines += ["", "## Privacy / exclusions", ""]
    lines.extend(f"- {x}" for x in report.explicit_exclusions)
    lines += ["", "Operational run data is diagnostic context only; it is not photographic evidence."]
    return "\n".join(lines) + "\n"


def export_review_progress(config, session: PilotSession,
                           current: PilotAuditSnapshot | None,
                           destination: Path) -> Path:
    """Create a shareable ZIP report; never include DB/photo/session bytes."""
    runs = load_activity_runs(config.log_path, limit=10000)
    report = build_review_progress_report(session, current, activity_runs=runs)
    destination = Path(destination)
    if destination.suffix.lower() != ".zip":
        destination = destination.with_suffix(".zip")
    destination.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=destination.name + ".", suffix=".tmp",
                                    dir=str(destination.parent))
    os.close(fd)
    tmp = Path(tmp_name)
    try:
        with zipfile.ZipFile(tmp, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            zf.writestr("review-progress.md", markdown_text(report))
            zf.writestr("review-progress.json", report.to_json(pretty=True) + "\n")
            zf.writestr("README.txt",
                        "Shareable PPA Phase 7 progress report.\n"
                        "Contains aggregate review/audit metrics and matching operational run summaries only.\n"
                        "It does not contain the catalogue database, source photographs, thumbnails, photo IDs, "
                        "raw paths, raw log messages, or the pilot-session artifact.\n")
        os.replace(tmp, destination)
    finally:
        tmp.unlink(missing_ok=True)
    return destination
